// prettier-ignore
import pcc from "@/public/images/projects/pcc.png";
import tabibi from "@/public/images/projects/tabibi.png";
import digitalmind from "@/public/images/projects/digitalmind.png";
import stockmanager from "@/public/images/projects/stockmanager.png";
import portfolio1 from "@/public/images/projects/portfolio-v1.png";
import portfolio2 from "@/public/images/projects/portfolio-v2.png";
import sms from "@/public/images/projects/sms.png";
import educonnect from "@/public/images/projects/educonnect.png";
import creon from "@/public/images/projects/creon.png";
import ibc from "@/public/images/projects/ibc.png";
import wifina from "@/public/images/projects/wifina.png";
import travelFlow from "@/public/images/projects/travel-flow.png";
import appartAli from "@/public/images/projects/appart-ali.png";
import zenHotel from "@/public/images/projects/zen-hotel.png";
import invoicr from "@/public/images/projects/invoicr.png";
import tabibiGallery from "./projectsGallery/tabibiGallery";
import stockGallery from "./projectsGallery/stockGallery";
import petTracker from "@/public/images/projects/pet-tracker.png";
import petTrackerGallery from "./projectsGallery/petTrackerGallery";
import avsm from "@/public/images/projects/avsm.png";
import odoc from "@/public/images/projects/odoc.png";
import idr from "@/public/images/projects/idr.png";
import { services } from "./servicesList";

const tech = (id: string) => {
  return services.find((service) => service.id === id);
};

const projects = [
  {
    image: avsm,
    title: "AVSM Volleyball Club",
    body: "Moroccan sports club needed a modern digital presence. Built a full-stack site with admin CMS for match management, news, team rosters, and photo galleries.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
      tech("framerMotion"),
    ],
    preview: "https://avsm.ma",
    github: null,
    year: 2025,
    category: "client",
    featured: true,
  },
  {
    image: odoc,
    title: "oDoc - Medical Practice Management",
    body: "Healthcare providers needed an all-in-one platform. Delivered appointment scheduling, patient records, WhatsApp chatbot, prescriptions, and accounting modules.",
    chips: [
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
      tech("supabase"),
    ],
    preview: "https://odoc.ma",
    github: null,
    year: 2025,
    inProgress: true,
    category: "client",
    featured: true,
  },
  {
    image: wifina,
    title: "Wifina - Loan Calculator & Pre-Approval",
    body: "Belgian fintech platform enabling instant loan calculations and pre-approval. Built a fully digital flow with banking API integrations.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("laravel"),
      tech("typescript"),
      tech("materialui"),
    ],
    preview: "https://wifina.be",
    github: null,
    year: "2024-2025",
    inProgress: false,
    category: "client",
    featured: true,
  },
  {
    image: invoicr,
    title: "Invoicr SaaS - Invoice Management",
    body: "SaaS platform for generating and managing invoices. Users can search, filter, and track invoices with a clean, efficient dashboard.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
      tech("supabase"),
    ],
    preview: "https://invoicrapp.com",
    github: null,
    year: 2025,
    inProgress: true,
    category: "client",
    featured: true,
  },
  {
    image: appartAli,
    title: "Appart Ali - Real Estate Platform",
    body: "Real estate business needed a listing platform with smart search. Integrated Guesty API and built an AI assistant to help users find properties.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
      tech("prisma"),
    ],
    preview: "https://appartali.com/",
    github: null,
    year: 2025,
    inProgress: false,
    category: "client",
    featured: true,
  },
  {
    image: idr,
    title: "Video Editor & Motion Designer Portfolio",
    body: "Creative professional needed a portfolio to showcase motion design work. Built a fast, visually striking site that highlights their experience.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
    ],
    preview: "https://www.idrissioussama.com",
    github: null,
    year: 2026,
    category: "client",
    featured: true,
  },
  {
    image: zenHotel,
    title: "Zen Hotel - Booking & Presentation",
    body: "Hotel needed an online presence with room showcases and a reservation system. Delivered a polished booking website with services and gallery.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
      tech("prisma"),
    ],
    preview: "https://zen-hotel.vercel.app/",
    github: null,
    year: 2025,
    inProgress: false,
    category: "client",
    featured: true,
  },
  {
    image: ibc,
    title: "IBC - Skills Anticipation Tool",
    body: "French employment stakeholders needed data-driven skills forecasting. Built an innovative tool to anticipate training needs in Centre-Val de Loire.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("typescript"),
      tech("materialui"),
    ],
    preview: "https://app.ibc.preprod.cysc.fr/",
    github: null,
    year: "2024-2025",
    notPublic: true,
    category: "client",
    featured: true,
  },
  {
    image: petTracker,
    title: "PetTracker Pro - GPS Tracking App",
    body: "Pet owners needed a way to track and manage their animals. Built a mobile app with real-time GPS, NFC tags, lost pet alerts, and ownership transfers.",
    chips: [tech("reactNative"), tech("typescript"), tech("supabase")],
    images: petTrackerGallery,
    preview: null,
    github: null,
    year: 2025,
    inProgress: false,
    isMobile: true,
    category: "client",
    featured: false,
  },
  {
    image: educonnect,
    title: "EduConnect - SaaS Landing Page",
    body: "School management SaaS needed a conversion-focused landing page. Designed and built a page showcasing features and pricing plans.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
      tech("framerMotion"),
    ],
    preview: "https://educonnect.jellyouness.com/",
    year: 2024,
    inProgress: false,
    category: "client",
    featured: false,
  },
  {
    image: sms,
    title: "SMS - School Management System",
    body: "Educational institution needed a system to manage students, teachers, and classes. Built a comprehensive school management web application.",
    chips: [
      tech("react"),
      tech("materialui"),
      tech("redux"),
      tech("javascript"),
    ],
    preview: "https://ihei.vercel.app",
    year: 2024,
    inProgress: false,
    category: "client",
    featured: false,
  },
  {
    image: digitalmind,
    title: "Digital Mind Agency - Website",
    body: "Agency needed a professional site to showcase services, projects, and team members. Delivered a clean, responsive static website.",
    chips: [tech("html"), tech("css"), tech("bootstrap"), tech("javascript")],
    preview: "https://jellyouness.github.io/Digital-Mind-Agency/",
    year: 2022,
    inProgress: false,
    category: "client",
    featured: false,
  },
  {
    image: stockmanager,
    title: "OPTIM'STOCK - Stock Manager",
    body: "Company needed internal stock management. Built a web application for tracking inventory and managing company stock.",
    chips: [
      tech("html"),
      tech("css"),
      tech("bootstrap"),
      tech("javascript"),
      tech("php"),
      tech("mysql"),
    ],
    images: stockGallery,
    github: "https://github.com/JellYouness/Stock-Management",
    preview: null,
    year: 2022,
    inProgress: false,
    category: "client",
    featured: false,
  },
  {
    image: pcc,
    title: "PCC Membership Management",
    body: "Palmeraie Country Club needed a system to manage member subscriptions. Built a membership and subscription management platform.",
    chips: [
      tech("html"),
      tech("css"),
      tech("bootstrap"),
      tech("javascript"),
      tech("php"),
      tech("mysql"),
    ],
    github: "https://github.com/JellYouness/Gestion-des-membres",
    preview: null,
    year: 2021,
    inProgress: false,
    category: "client",
    featured: false,
  },
  {
    image: travelFlow,
    title: "Travel Flow - TSP Solver",
    body: "Algorithm visualization tool for route optimization and the Traveling Salesman Problem.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("materialui"),
      tech("typescript"),
      tech("python"),
      tech("google"),
    ],
    preview: "https://travel-flow-tsp.vercel.app/",
    github: "https://github.com/JellYouness/travel-flow-tsp",
    year: 2024,
    inProgress: false,
    category: "personal",
    featured: false,
  },
  {
    image: creon,
    title: "Creon AI - NFT Platform Landing Page",
    body: "Design exercise — landing page for an NFT blockchain platform.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
    ],
    preview: "https://creon.jellyouness.com/",
    github: "https://github.com/JellYouness/creon-nft-landing-page",
    year: 2024,
    inProgress: false,
    category: "personal",
    featured: false,
  },
  {
    image: tabibi,
    title: "Tabibi - Medical Emergency Management",
    body: "Medical emergency management web application built as a university capstone project.",
    chips: [
      tech("react"),
      tech("materialui"),
      tech("redux"),
      tech("javascript"),
      tech("laravel"),
      tech("mysql"),
    ],
    images: tabibiGallery,
    github: "https://github.com/JellYouness/Tabibi",
    preview: null,
    year: 2023,
    inProgress: false,
    category: "personal",
    featured: false,
  },
  {
    image: portfolio2,
    title: "Personal Portfolio v2",
    body: "Previous version of this portfolio site showcasing web development skills.",
    chips: [
      tech("nextjs"),
      tech("react"),
      tech("tailwind"),
      tech("typescript"),
      tech("framerMotion"),
    ],
    preview: "https://jellyouness.com",
    year: "2024-2025",
    inProgress: false,
    category: "personal",
    featured: false,
  },
  {
    image: portfolio1,
    title: "Personal Portfolio v1",
    body: "First portfolio version built with React and Material UI.",
    chips: [
      tech("react"),
      tech("materialui"),
      tech("javascript"),
      tech("framerMotion"),
    ],
    preview: "https://v1.jellyouness.com",
    github: "https://github.com/JellYouness/portfolio",
    year: 2023,
    inProgress: false,
    category: "personal",
    featured: false,
  },
];

export default projects;
